#!/usr/bin/env python3

import argparse
from pilmoji import Pilmoji
from PIL import Image, ImageDraw, ImageFont


def create_png_from_char(char, font_path, font_size, output_path):
    SCALE_FACTOR = 4
    font_size = 96
    font = ImageFont.load_default(font_size)

    # Calculate the width and height of the text to be drawn
    bbox_left, bbox_top, bbox_right, bbox_bottom  = font.getbbox(char)

    image = Image.new("RGBA", (2* bbox_right, int(bbox_bottom*1.1)), "#00000000")
    draw = Pilmoji(image)

    draw.text(
        (0, -bbox_bottom),
        char,
        fill="#00000000",
        font=font,
        embedded_color=True,
    )

    if output_path:
        image.save(output_path)
        print(f"Image saved to {output_path}")
    else:
        image.show()



def main():
    parser = argparse.ArgumentParser(
        description="Create a PNG image from a text character."
    )
    parser.add_argument(
        "character", type=str, help="The character to create a PNG from."
    )
    parser.add_argument(
        "--font", type=str, default="./emoji.ttf", help="Path to the font file."
    )
    parser.add_argument("--fontsize", type=int, default=109, help="Font size.")
    parser.add_argument(
        "--imageheight",
        type=int,
        nargs=3,
        default=300,
        help="Height of the output image.",
    )
    parser.add_argument("--output", type=str, help="Output file path.")

    args = parser.parse_args()

    create_png_from_char(
        args.character,
        font_path=args.font,
        font_size=args.fontsize,
        output_path=args.output,
    )


"""
I created the textures in this game with
    ./text-to-png \
          '🍏🍎🍐🍊🍋🍌🍉🍇🍓🍈🍒🍑🍍🥭🥥🥝🍅🍆🌽🥕🥔🥬🥒🥦🍞🥖🥯🥨🥞🧇🍳🍔🍟🍕🌭🥗🍝🍜🍲🍣🍱🍤🍙🍚🍛🍥🍦🍧🍨🍩🍪🎂🍰🧁🍫🍬🍭🍮🍯🥛☕🍵🍺🍻🥂🍷🥃' \
            --font=emoji.ttf --output=emoji.png
"""
if __name__ == "__main__":
    main()
